# GitHub Actions secrets for the iron-static repo.
#
# Input secrets — set as environment variables before running terraform apply:
#   export TF_VAR_gemini_api_key=$GEMINI_API_KEY
#   export TF_VAR_gh_pat=$GH_PAT
#
# Generated secrets (no manual input needed — Terraform creates them from GCP resources):
#   GCS_SA_KEY — derived from google_service_account_key.github_actions
#
# The sensitive = true flag in variables.tf prevents values from appearing
# in plan/apply output. State is stored in GCS (see main.tf backend config).

resource "github_actions_secret" "gemini_api_key" {
  repository      = local.repository
  secret_name     = "GEMINI_API_KEY"
  plaintext_value = var.gemini_api_key
}

resource "github_actions_secret" "gh_pat" {
  repository      = local.repository
  secret_name     = "GH_PAT"
  plaintext_value = var.gh_pat
}

# GCS service account key — generated by Terraform, base64-decoded for the GitHub secret.
# Rotation: terraform taint google_service_account_key.github_actions && terraform apply
resource "github_actions_secret" "gcs_sa_key" {
  repository      = local.repository
  secret_name     = "GCS_SA_KEY"
  plaintext_value = base64decode(google_service_account_key.github_actions.private_key)
}
