# GitHub Actions secrets for the iron-static repo.
#
# Input secrets — set as environment variables before running terraform apply:
#   export TF_VAR_gemini_api_key=$GEMINI_API_KEY
#   export TF_VAR_gh_pat=$GH_PAT
#
# Generated secrets (no manual input needed — Terraform creates them from GCP resources):
#   GCS_SA_KEY — derived from google_service_account_key.github_actions
#
# The sensitive = true flag in variables.tf prevents values from appearing
# in plan/apply output. State is stored in GCS (see main.tf backend config).

resource "github_actions_secret" "gemini_api_key" {
  repository      = local.repository
  secret_name     = "GEMINI_API_KEY"
  plaintext_value = var.gemini_api_key
}

resource "github_actions_secret" "gh_pat" {
  repository      = local.repository
  secret_name     = "GH_PAT"
  plaintext_value = var.gh_pat
}

# GCS service account key — generated by Terraform, base64-decoded for the GitHub secret.
# Rotation: terraform taint google_service_account_key.github_actions && terraform apply
resource "github_actions_secret" "gcs_sa_key" {
  repository      = local.repository
  secret_name     = "GCS_SA_KEY"
  plaintext_value = base64decode(google_service_account_key.github_actions.private_key)
}

# ---------------------------------------------------------------------------
# Instagram Content Publishing API
# ---------------------------------------------------------------------------
# Prerequisites:
#   1. Instagram Professional account (Business or Creator)
#   2. Facebook Page connected to the Instagram account
#   3. Meta app with instagram_content_publish permission approved
#   4. Long-lived User Access Token (~60 days). Generate via:
#      https://developers.facebook.com/tools/explorer/
#      Required scopes: instagram_content_publish, instagram_basic, pages_show_list
#
# Token refresh: long-lived tokens can be refreshed before expiry via:
#   GET /oauth/access_token?grant_type=fb_exchange_token&client_id=...&client_secret=...&fb_exchange_token=...
#
# Check token validity: python scripts/post_instagram.py --check-token
#
# Set before running terraform apply:
#   export TF_VAR_instagram_access_token="<long-lived-token>"
#   export TF_VAR_instagram_user_id="<numeric-user-id>"

resource "github_actions_secret" "instagram_access_token" {
  repository      = local.repository
  secret_name     = "INSTAGRAM_ACCESS_TOKEN"
  plaintext_value = var.instagram_access_token
}

resource "github_actions_secret" "instagram_user_id" {
  repository      = local.repository
  secret_name     = "INSTAGRAM_USER_ID"
  plaintext_value = var.instagram_user_id
}
