#!/usr/bin/env zsh
# IRON STATIC Stream Deck command wrapper — auto-generated by generate_profile.py
# Button: Session Start
exec "/Users/darnold/git/iron-static/streamdeck/buttons/01_session_start.sh"
