#!/usr/bin/env zsh
# IRON STATIC Stream Deck command wrapper — auto-generated by generate_profile.py
# Button: Ableton Launch
exec "/Users/darnold/git/iron-static/streamdeck/buttons/03_ableton_launch.sh"
