#!/usr/bin/env zsh
# IRON STATIC Stream Deck command wrapper — auto-generated by generate_profile.py
# Button: VELA Generate
exec "/Users/darnold/git/iron-static/streamdeck/buttons/04_vela_generate.sh"
