#!/usr/bin/env zsh
# IRON STATIC Stream Deck command wrapper — auto-generated by generate_profile.py
# Button: Run Brainstorm
exec "/Users/darnold/git/iron-static/streamdeck/buttons/05_run_brainstorm.sh"
