#!/usr/bin/env zsh
# IRON STATIC Stream Deck command wrapper — auto-generated by generate_profile.py
# Button: Transport Toggle
exec "/Users/darnold/git/iron-static/streamdeck/buttons/07_transport_toggle.sh"
