#!/usr/bin/env zsh
# IRON STATIC Stream Deck command wrapper — auto-generated by generate_profile.py
# Button: Health Check
exec "/Users/darnold/git/iron-static/streamdeck/buttons/08_health_check.sh"
