#!/usr/bin/env zsh
# IRON STATIC Stream Deck encoder command — auto-generated by generate_profile.py
# Encoder: BPM Info
source ~/.zshrc 2>/dev/null
cd /Users/darnold/git/iron-static && python scripts/manage_songs.py list
