#!/usr/bin/env zsh
# IRON STATIC Stream Deck encoder command — auto-generated by generate_profile.py
# Encoder: Pigments M1
source ~/.zshrc 2>/dev/null
cd /Users/darnold/git/iron-static && python streamdeck/dial_bridge.py --dial 3 --delta 0
