#!/usr/bin/env zsh
# IRON STATIC Stream Deck encoder command — auto-generated by generate_profile.py
# Encoder: Bridge
source ~/.zshrc 2>/dev/null
cd /Users/darnold/git/iron-static && python scripts/bridge_client.py --ping
